### ISSUE TITLE
[ENHANCEMENT] Add Code Climate for maintainability, unit test and Add Go Reports

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/auth#4]
## Issue
- add maintainability checker, tester function and reporting for  package

## Tasks
- [x] add badge maintainability
- [x] add badge test coverage
- [x] add go report badge
