### ISSUE TITLE
[ENHANCEMENT] Create method for get user detail by its access token

### ISSUE THREAD

**Issue by setiadijoe** [sapawarga/auth#8]
## Issue
User give access token and get user detail for accessing other moduls

## Tasks
- [x] create endpoint for handling access token and get user detail
- [x] create unit test
- [x] create rpc for handle get user detail by access token
